var users;
users = [];
// let user1:{username:string,userid:number};
// user1 = {username:"nafiur",userid:101};
// console.log(user1);
var user1;
user1 = { userName: "Nafiur", userId: 101 };
users.push(user1);
var user2;
user2 = { userName: "Anisul", userId: 105 };
users.push(user2);
console.log(users);
